name: Deploy Docker Image to Target Environment
on:
  push:
    branches:
      - main

jobs:
  build-image: 
    runs-on: [self-hosted, averyonprem-ul]
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Image
      run: docker build -t homeautoapi:latest .

    - name: Stop and Remove Existing Container
      run: |
        sudo docker stop homeautoapi || true
        sudo docker rm homeautoapi || true

    - name: Run New Container
      run: |
        sudo docker run -d --name homeautoapi -p 8080:8080 homeautoapi:latest --restart unless-stopped --env-file /opt/homeautoapi/.env homeautoapi:latest
